# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HackerNews

  target 'HackerNews-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  end

  target 'HackerNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HackerNews-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HackerNews-tvOS

  target 'HackerNews-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
